// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc1Xih9en2naE5f5e4qLrJddvMOF-NFfY',
    appId: '1:877870867813:web:d04daa127ed87797f8ed8c',
    messagingSenderId: '877870867813',
    projectId: 'quizfy-163bd',
    authDomain: 'quizfy-163bd.firebaseapp.com',
    storageBucket: 'quizfy-163bd.firebasestorage.app',
    measurementId: 'G-LXDB8ZK5MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKyeMdOdCpzrdhPlxUioWGAFbJzTgnUtU',
    appId: '1:877870867813:android:571b452453406b47f8ed8c',
    messagingSenderId: '877870867813',
    projectId: 'quizfy-163bd',
    storageBucket: 'quizfy-163bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFacku561voEjGZVUwx4B_jGS-QGjBZ9s',
    appId: '1:877870867813:ios:de02dd6a3f07538ef8ed8c',
    messagingSenderId: '877870867813',
    projectId: 'quizfy-163bd',
    storageBucket: 'quizfy-163bd.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFacku561voEjGZVUwx4B_jGS-QGjBZ9s',
    appId: '1:877870867813:ios:de02dd6a3f07538ef8ed8c',
    messagingSenderId: '877870867813',
    projectId: 'quizfy-163bd',
    storageBucket: 'quizfy-163bd.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc1Xih9en2naE5f5e4qLrJddvMOF-NFfY',
    appId: '1:877870867813:web:bb4793eff851e38ff8ed8c',
    messagingSenderId: '877870867813',
    projectId: 'quizfy-163bd',
    authDomain: 'quizfy-163bd.firebaseapp.com',
    storageBucket: 'quizfy-163bd.firebasestorage.app',
    measurementId: 'G-WTYK7W03T8',
  );
}
